const font_family_list = [
    { label: 'Default', value: 'Arial' },
    { label: 'Arial', value: 'Arial' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Times New Roman', value: 'Times New Roman' },
    { label: 'Arial Black', value: 'Arial Black' },
    { label: 'Arial Narrow', value: 'Arial Narrow' },
    { label: 'Arial Narrow Special', value: 'Arial Narrow Special' },
    { label: 'Arial Rounded MT', value: 'Arial Rounded MT' },
    { label: 'Arial Special', value: 'Arial Special' },
    { label: 'Arial Unicode MS', value: 'Arial Unicode MS' },
    { label: 'Abadi MT', value: 'Abadi MT' },
    { label: 'Agency FB', value: 'Agency FB' },
    { label: 'Aharoni Bold', value: 'Aharoni Bold' },
    { label: 'Aldhabi', value: 'Aldhabi' },
    { label: 'Algerian', value: 'Algerian' },
    { label: 'Almanac MT', value: 'Almanac MT' },
    { label: 'American Uncial', value: 'American Uncial' },
    { label: 'Andale Mono', value: 'Andale Mono' },
    { label: 'Andalus', value: 'Andalus' },
    { label: 'Andy', value: 'Andy' },
    { label: 'AngsanaUPC', value: 'AngsanaUPC' },
    { label: 'Angsana New', value: 'Angsana New' },
    { label: 'Aparajita', value: 'Aparajita' },
    { label: 'Arabic Transparent', value: 'Arabic Transparent' },
    { label: 'Arabic Typesetting', value: 'Arabic Typesetting' },
    { label: 'Augsburger Initials', value: 'Augsburger Initials' },
    { label: 'Avenir Next LT Pro', value: 'Avenir Next LT Pro' },
    { label: 'Bahnschrift', value: 'Bahnschrift' },
    { label: 'Baskerville Old Face', value: 'Baskerville Old Face' },
    { label: 'Batang & BatangChe', value: 'Batang & BatangChe' },
    { label: 'Bauhaus 93', value: 'Bauhaus 93' },
    { label: 'Beesknees ITC', value: 'Beesknees ITC' },
    { label: 'Bell MT', value: 'Bell MT' },
    { label: 'Bembo', value: 'Bembo' },
    { label: 'Berlin Sans FB', value: 'Berlin Sans FB' },
    { label: 'Bernard MT Condensed', value: 'Bernard MT Condensed' },
    { label: 'Bickley Script', value: 'Bickley Script' },
    { label: 'Biome', value: 'Biome' },
    { label: 'BIZ UDGothic', value: 'BIZ UDGothic' },
    { label: 'BIZ UDMincho Medium', value: 'BIZ UDMincho Medium' },
    { label: 'Blackadder ITC', value: 'Blackadder ITC' },
    { label: 'Bodoni MT', value: 'Bodoni MT' },
    { label: 'Bodoni MT Condensed', value: 'Bodoni MT Condensed' },
    { label: 'Bon Apetit MT', value: 'Bon Apetit MT' },
    { label: 'Bookman Old Style', value: 'Bookman Old Style' },
    { label: 'Bookshelf Symbol', value: 'Bookshelf Symbol' },
    { label: 'Book Antiqua', value: 'Book Antiqua' },
    { label: 'Bradley Hand ITC', value: 'Bradley Hand ITC' },
    { label: 'Braggadocio', value: 'Braggadocio' },
    { label: 'BriemScript', value: 'BriemScript' },
    { label: 'Britannic Bold', value: 'Britannic Bold' },
    { label: 'Broadway', value: 'Broadway' },
    { label: 'BrowalliaUPC', value: 'BrowalliaUPC' },
    { label: 'Browallia New', value: 'Browallia New' },
    { label: 'Brush Script MT', value: 'Brush Script MT' },
    { label: 'Calibri', value: 'Calibri' },
    { label: 'Californian FB', value: 'Californian FB' },
    { label: 'Calisto MT', value: 'Calisto MT' },
    { label: 'Cambria', value: 'Cambria' },
    { label: 'Cambria Math', value: 'Cambria Math' },
    { label: 'Candara', value: 'Candara' },
    { label: 'Cariadings', value: 'Cariadings' },
    { label: 'Castellar', value: 'Castellar' },
    { label: 'Cavolini', value: 'Cavolini' },
    { label: 'Centaur', value: 'Centaur' },
    { label: 'Century', value: 'Century' },
    { label: 'Century Gothic', value: 'Century Gothic' },
    { label: 'Century Schoolbook', value: 'Century Schoolbook' },
    { label: 'Chiller', value: 'Chiller' },
    { label: 'Colonna MT', value: 'Colonna MT' },
    { label: 'Comic Sans MS', value: 'Comic Sans MS' },
    { label: 'Consolas', value: 'Consolas' },
    { label: 'Constantia', value: 'Constantia' },
    { label: 'Contemporary Brush', value: 'Contemporary Brush' },
    { label: 'Cooper Black', value: 'Cooper Black' },
    { label: 'Copperplate Gothic', value: 'Copperplate Gothic' },
    { label: 'Corbel', value: 'Corbel' },
    { label: 'CordiaUPC', value: 'CordiaUPC' },
    { label: 'Courier New', value: 'Courier New' },
    { label: 'Curlz MT', value: 'Curlz MT' },
    { label: 'Dante', value: 'Dante' },
    { label: 'DaunPenh', value: 'DaunPenh' },
    { label: 'David', value: 'David' },
    { label: 'Daytona', value: 'Daytona' },
    { label: 'Desdemona', value: 'Desdemona' },
    { label: 'DFKai-SB', value: 'DFKai-SB' },
    { label: 'DilleniaUPC', value: 'DilleniaUPC' },
    { label: 'Directions MT', value: 'Directions MT' },
    { label: 'DokChampa', value: 'DokChampa' },
    { label: 'Dotum & DotumChe', value: 'Dotum & DotumChe' },
    { label: 'Ebrima', value: 'Ebrima' },
    { label: 'Eckmann', value: 'Eckmann' },
    { label: 'Edda', value: 'Edda' },
    { label: 'Edwardian Script ITC', value: 'Edwardian Script ITC' },
    { label: 'Elephant', value: 'Elephant' },
    { label: 'Engravers MT', value: 'Engravers MT' },
    { label: 'Enviro', value: 'Enviro' },
    { label: 'Eras ITC', value: 'Eras ITC' },
    { label: 'Estrangelo Edessa', value: 'Estrangelo Edessa' },
    { label: 'EucrosiaUPC', value: 'EucrosiaUPC' },
    { label: 'Euphemia', value: 'Euphemia' },
    { label: 'Eurostile', value: 'Eurostile' },
    { label: 'FangSong', value: 'FangSong' },
    { label: 'Felix Titling', value: 'Felix Titling' },
    { label: 'Fine Hand', value: 'Fine Hand' },
    { label: 'Fixed Miriam Transparent', value: 'Fixed Miriam Transparent' },
    { label: 'Flexure', value: 'Flexure' },
    { label: 'Footlight MT', value: 'Footlight MT' },
    { label: 'Forte', value: 'Forte' },
    { label: 'Franklin Gothic', value: 'Franklin Gothic' },
    { label: 'Franklin Gothic Medium', value: 'Franklin Gothic Medium' },
    { label: 'FrankRuehl', value: 'FrankRuehl' },
    { label: 'FreesiaUPC', value: 'FreesiaUPC' },
    { label: 'Freestyle Script', value: 'Freestyle Script' },
    { label: 'French Script MT', value: 'French Script MT' },
    { label: 'Futura', value: 'Futura' },
    { label: 'Gabriola', value: 'Gabriola' },
    { label: 'Gadugi', value: 'Gadugi' },
    { label: 'Garamond', value: 'Garamond' },
    { label: 'Garamond MT', value: 'Garamond MT' },
    { label: 'Gautami', value: 'Gautami' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Georgia Ref', value: 'Georgia Ref' },
    { label: 'Gigi', value: 'Gigi' },
    { label: 'Gill Sans MT', value: 'Gill Sans MT' },
    { label: 'Gill Sans MT Condensed', value: 'Gill Sans MT Condensed' },
    { label: 'Gisha', value: 'Gisha' },
    { label: 'Gloucester', value: 'Gloucester' },
    { label: 'Goudy Old Style', value: 'Goudy Old Style' },
    { label: 'Goudy Stout', value: 'Goudy Stout' },
    { label: 'Gradl', value: 'Gradl' },
    { label: 'Grotesque', value: 'Grotesque' },
    { label: 'Gulim & GulimChe', value: 'Gulim & GulimChe' },
    { label: 'Gungsuh & GungsuhChe', value: 'Gungsuh & GungsuhChe' },
    { label: 'Hadassah Friedlaender', value: 'Hadassah Friedlaender' },
    { label: 'Haettenschweiler', value: 'Haettenschweiler' },
    { label: 'Harlow Solid Italic', value: 'Harlow Solid Italic' },
    { label: 'Harrington', value: 'Harrington' },
    { label: 'HGGothicE', value: 'HGGothicE' },
    { label: 'HGMinchoE', value: 'HGMinchoE' },
    { label: 'HGSoeiKakugothicUB', value: 'HGSoeiKakugothicUB' },
    { label: 'High Tower Text', value: 'High Tower Text' },
    { label: 'Holidays MT', value: 'Holidays MT' },
    { label: 'HoloLens MDL2 Assets', value: 'HoloLens MDL2 Assets' },
    { label: 'Impact', value: 'Impact' },
    { label: 'Imprint MT Shadow', value: 'Imprint MT Shadow' },
    { label: 'Informal Roman', value: 'Informal Roman' },
    { label: 'IrisUPC', value: 'IrisUPC' },
    { label: 'Iskoola Pota', value: 'Iskoola Pota' },
    { label: 'JasmineUPC', value: 'JasmineUPC' },
    { label: 'Javanese Text', value: 'Javanese Text' },
    { label: 'Jokerman', value: 'Jokerman' },
    { label: 'Juice ITC', value: 'Juice ITC' },
    { label: 'KaiTi', value: 'KaiTi' },
    { label: 'Kalinga', value: 'Kalinga' },
    { label: 'Kartika', value: 'Kartika' },
    { label: 'Keystrokes MT', value: 'Keystrokes MT' },
    { label: 'Khmer UI', value: 'Khmer UI' },
    { label: 'Kino MT', value: 'Kino MT' },
    { label: 'KodchiangUPC', value: 'KodchiangUPC' },
    { label: 'Kokila', value: 'Kokila' },
    { label: 'Kristen ITC', value: 'Kristen ITC' },
    { label: 'Kunstler Script', value: 'Kunstler Script' },
    { label: 'Lao UI', value: 'Lao UI' },
    { label: 'Latha', value: 'Latha' },
    { label: 'LCD', value: 'LCD' },
    { label: 'Leelawadee', value: 'Leelawadee' },
    { label: 'Levenim MT', value: 'Levenim MT' },
    { label: 'LilyUPC', value: 'LilyUPC' },
    { label: 'Lucida Blackletter', value: 'Lucida Blackletter' },
    { label: 'Lucida Bright', value: 'Lucida Bright' },
    { label: 'Lucida Bright Math', value: 'Lucida Bright Math' },
    { label: 'Lucida Calligraphy', value: 'Lucida Calligraphy' },
    { label: 'Lucida Console', value: 'Lucida Console' },
    { label: 'Lucida Fax', value: 'Lucida Fax' },
    { label: 'Lucida Handwriting', value: 'Lucida Handwriting' },
    { label: 'Lucida Sans', value: 'Lucida Sans' },
    { label: 'Lucida Sans Typewriter', value: 'Lucida Sans Typewriter' },
    { label: 'Lucida Sans Unicode', value: 'Lucida Sans Unicode' },
    { label: 'Magneto', value: 'Magneto' },
    { label: 'Maiandra GD', value: 'Maiandra GD' },
    { label: 'Malgun Gothic', value: 'Malgun Gothic' },
    { label: 'Mangal', value: 'Mangal' },
    { label: 'Map Symbols', value: 'Map Symbols' },
    { label: 'Marlett', value: 'Marlett' },
    { label: 'Matisse ITC', value: 'Matisse ITC' },
    { label: 'Matura MT Script Capitals', value: 'Matura MT Script Capitals' },
    { label: 'McZee', value: 'McZee' },
    { label: 'Mead Bold', value: 'Mead Bold' },
    { label: 'Meiryo', value: 'Meiryo' },
    { label: 'Mercurius Script MT Bold', value: 'Mercurius Script MT Bold' },
    { label: 'Microsoft GothicNeo', value: 'Microsoft GothicNeo' },
    { label: 'Microsoft Himalaya', value: 'Microsoft Himalaya' },
    { label: 'Microsoft JhengHei', value: 'Microsoft JhengHei' },
    { label: 'Microsoft JhengHei UI', value: 'Microsoft JhengHei UI' },
    { label: 'Microsoft New Tai Lue', value: 'Microsoft New Tai Lue' },
    { label: 'Microsoft PhagsPa', value: 'Microsoft PhagsPa' },
    { label: 'Microsoft Sans Serif', value: 'Microsoft Sans Serif' },
    { label: 'Microsoft Tai Le', value: 'Microsoft Tai Le' },
    { label: 'Microsoft Uighur', value: 'Microsoft Uighur' },
    { label: 'Microsoft YaHei', value: 'Microsoft YaHei' },
    { label: 'Microsoft YaHei UI', value: 'Microsoft YaHei UI' },
    { label: 'Microsoft Yi Baiti', value: 'Microsoft Yi Baiti' },
    { label: 'MingLiU', value: 'MingLiU' },
    { label: 'MingLiU-ExtB', value: 'MingLiU-ExtB' },
    { label: 'MingLiU_HKSCS', value: 'MingLiU_HKSCS' },
    { label: 'MingLiU_HKSCS-ExtB', value: 'MingLiU_HKSCS-ExtB' },
    { label: 'Minion Web', value: 'Minion Web' },
    { label: 'Miriam', value: 'Miriam' },
    { label: 'Miriam Fixed', value: 'Miriam Fixed' },
    { label: 'Mistral', value: 'Mistral' },
    { label: 'Modern Love', value: 'Modern Love' },
    { label: 'Modern No. 20', value: 'Modern No. 20' },
    { label: 'Mongolian Baiti', value: 'Mongolian Baiti' },
    { label: 'Monotype.com', value: 'Monotype.com' },
    { label: 'Monotype Corsiva', value: 'Monotype Corsiva' },
    { label: 'Monotype Sorts', value: 'Monotype Sorts' },
    { label: 'MoolBoran', value: 'MoolBoran' },
    { label: 'MS Gothic', value: 'MS Gothic' },
    { label: 'MS LineDraw', value: 'MS LineDraw' },
    { label: 'MS Mincho', value: 'MS Mincho' },
    { label: 'MS Outlook', value: 'MS Outlook' },
    { label: 'MS PGothic', value: 'MS PGothic' },
    { label: 'MS PMincho', value: 'MS PMincho' },
    { label: 'MS Reference', value: 'MS Reference' },
    { label: 'MS UI Gothic', value: 'MS UI Gothic' },
    { label: 'MT Extra', value: 'MT Extra' },
    { label: 'MV Boli', value: 'MV Boli' },
    { label: 'Myanmar Text', value: 'Myanmar Text' },
    { label: 'Narkisim', value: 'Narkisim' },
    { label: 'News Gothic MT', value: 'News Gothic MT' },
    { label: 'New Caledonia', value: 'New Caledonia' },
    { label: 'Niagara', value: 'Niagara' },
    { label: 'Nirmala UI', value: 'Nirmala UI' },
    { label: 'Nyala', value: 'Nyala' },
    { label: 'OCR-B-Digits', value: 'OCR-B-Digits' },
    { label: 'OCRB', value: 'OCRB' },
    { label: 'OCR A Extended', value: 'OCR A Extended' },
    { label: 'Old English Text MT', value: 'Old English Text MT' },
    { label: 'Onyx', value: 'Onyx' },
    { label: 'Palace Script MT', value: 'Palace Script MT' },
    { label: 'Palatino Linotype', value: 'Palatino Linotype' },
    { label: 'Papyrus', value: 'Papyrus' },
    { label: 'Parade', value: 'Parade' },
    { label: 'Parchment', value: 'Parchment' },
    { label: 'Parties MT', value: 'Parties MT' },
    { label: 'Peignot Medium', value: 'Peignot Medium' },
    { label: 'Pepita MT', value: 'Pepita MT' },
    { label: 'Perpetua', value: 'Perpetua' },
    { label: 'Perpetua Titling MT', value: 'Perpetua Titling MT' },
    { label: 'Placard Condensed', value: 'Placard Condensed' },
    { label: 'Plantagenet Cherokee', value: 'Plantagenet Cherokee' },
    { label: 'Playbill', value: 'Playbill' },
    { label: 'PMingLiU', value: 'PMingLiU' },
    { label: 'PMingLiU-ExtB', value: 'PMingLiU-ExtB' },
    { label: 'Poor Richard', value: 'Poor Richard' },
    { label: 'Posterama', value: 'Posterama' },
    { label: 'Pristina', value: 'Pristina' },
    { label: 'Raavi', value: 'Raavi' },
    { label: 'Rage Italic', value: 'Rage Italic' },
    { label: 'Ransom', value: 'Ransom' },
    { label: 'Ravie', value: 'Ravie' },
    { label: 'RefSpecialty', value: 'RefSpecialty' },
    { label: 'Rockwell', value: 'Rockwell' },
    { label: 'Rockwell Nova', value: 'Rockwell Nova' },
    { label: 'Rod', value: 'Rod' },
    { label: 'Runic MT Condensed', value: 'Runic MT Condensed' },
    { label: 'Sabon Next LT', value: 'Sabon Next LT' },
    { label: 'Sagona', value: 'Sagona' },
    { label: 'Sakkal Majalla', value: 'Sakkal Majalla' },
    { label: 'Script MT Bold', value: 'Script MT Bold' },
    { label: 'Segoe Chess', value: 'Segoe Chess' },
    { label: 'Segoe Print', value: 'Segoe Print' },
    { label: 'Segoe Script', value: 'Segoe Script' },
    { label: 'Segoe UI', value: 'Segoe UI' },
    { label: 'Segoe UI Symbol', value: 'Segoe UI Symbol' },
    { label: 'Selawik', value: 'Selawik' },
    { label: 'Shonar Bangla', value: 'Shonar Bangla' },
    { label: 'Showcard Gothic', value: 'Showcard Gothic' },
    { label: 'Shruti', value: 'Shruti' },
    { label: 'Signs MT', value: 'Signs MT' },
    { label: 'SimHei', value: 'SimHei' },
    { label: 'Simplified Arabic Fixed', value: 'Simplified Arabic Fixed' },
    { label: 'SimSun', value: 'SimSun' },
    { label: 'SimSun-ExtB', value: 'SimSun-ExtB' },
    { label: 'Sitka', value: 'Sitka' },
    { label: 'NSimSun', value: 'NSimSun' },
    { label: 'Snap ITC', value: 'Snap ITC' },
    { label: 'Sports MT', value: 'Sports MT' },
    { label: 'STCaiyun', value: 'STCaiyun' },
    { label: 'Stencil', value: 'Stencil' },
    { label: 'STFangsong', value: 'STFangsong' },
    { label: 'STHupo', value: 'STHupo' },
    { label: 'STKaiti', value: 'STKaiti' },
    { label: 'Stop', value: 'Stop' },
    { label: 'STXihei', value: 'STXihei' },
    { label: 'STXingkai', value: 'STXingkai' },
    { label: 'STXinwei', value: 'STXinwei' },
    { label: 'STZhongsong', value: 'STZhongsong' },
    { label: 'Sylfaen', value: 'Sylfaen' },
    { label: 'Symbol', value: 'Symbol' },
    { label: 'Tahoma', value: 'Tahoma' },
    { label: 'Tempo Grunge', value: 'Tempo Grunge' },
    { label: 'Tempus Sans ITC', value: 'Tempus Sans ITC' },
    { label: 'Temp Installer Font', value: 'Temp Installer Font' },
    { label: 'The Hand', value: 'The Hand' },
    { label: 'The Serif Hand', value: 'The Serif Hand' },
    { label: 'Times New Roman', value: 'Times New Roman' },
    { label: 'Times New Roman Special', value: 'Times New Roman Special' },
    { label: 'Tisa Offc Serif Pro', value: 'Tisa Offc Serif Pro' },
    { label: 'Traditional Arabic', value: 'Traditional Arabic' },
    { label: 'Transport MT', value: 'Transport MT' },
    { label: 'Trebuchet MS', value: 'Trebuchet MS' },
    { label: 'Tunga', value: 'Tunga' },
    { label: 'Tw Cen MT', value: 'Tw Cen MT' },
    { label: 'Univers', value: 'Univers' },
    { label: 'Urdu Typesetting', value: 'Urdu Typesetting' },
    { label: 'Utsaah', value: 'Utsaah' },
    { label: 'Vacation MT', value: 'Vacation MT' },
    { label: 'Vani', value: 'Vani' },
    { label: 'Verdana', value: 'Verdana' },
    { label: 'Verdana Ref', value: 'Verdana Ref' },
    { label: 'Vijaya', value: 'Vijaya' },
    { label: 'Viner Hand ITC', value: 'Viner Hand ITC' },
    { label: 'Vivaldi', value: 'Vivaldi' },
    { label: 'Vixar ASCI', value: 'Vixar ASCI' },
    { label: 'Vladimir Script', value: 'Vladimir Script' },
    { label: 'Vrinda', value: 'Vrinda' },
    { label: 'Walbaum', value: 'Walbaum' },
    { label: 'Webdings', value: 'Webdings' },
    { label: 'Westminster', value: 'Westminster' },
    { label: 'Wide Latin', value: 'Wide Latin' },
    { label: 'Wingdings', value: 'Wingdings' },
]

export default font_family_list;